# Generated by Django 6.0.3 on 2026-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10),
        ),
    ]
