# Generated by Django 6.0.3 on 2026-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API Synced')], default='local', max_length=10),
        ),
    ]
