# Generated by Django 6.0.3 on 2026-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='live_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
