# Generated by Django 6.0.3 on 2026-04-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_live_altitude_flight_live_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('status', 'Status Change'), ('schedule', 'Schedule Change'), ('live', 'Live Data Change'), ('mixed', 'Mixed Change')], default='status', max_length=20)),
                ('source_type_snapshot', models.CharField(choices=[('local', 'Local'), ('api', 'API Synced')], default='local', max_length=10)),
                ('scheduled_departure_snapshot', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arrival_snapshot', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_snapshot', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_snapshot', models.DateTimeField(blank=True, null=True)),
                ('departure_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('arrival_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('is_disruption_event', models.BooleanField(default=False)),
                ('status_changed', models.BooleanField(default=False)),
                ('schedule_changed', models.BooleanField(default=False)),
                ('live_data_changed', models.BooleanField(default=False)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_history_entries', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Flight Status History',
                'verbose_name_plural': 'Flight Status History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
