# Generated by Django 6.0.3 on 2026-04-10 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_aircraft_ai_registr_47b3ca_idx_and_more'),
        ('airlines', '0002_airline_airlines_ai_name_d4975d_idx_and_more'),
        ('airports', '0003_airport_airports_ai_name_b30727_idx_and_more'),
        ('flights', '0005_flightstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API Synced')], db_index=True, default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['source_type'], name='flights_fli_source__bd0063_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['scheduled_departure'], name='flights_fli_schedul_b040af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['scheduled_arrival'], name='flights_fli_schedul_e767ce_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['airline', 'status'], name='flights_fli_airline_cfe926_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstatushistory',
            index=models.Index(fields=['flight', '-changed_at'], name='flights_fli_flight__725ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstatushistory',
            index=models.Index(fields=['new_status'], name='flights_fli_new_sta_66e94d_idx'),
        ),
        migrations.AddIndex(
            model_name='flightstatushistory',
            index=models.Index(fields=['change_type'], name='flights_fli_change__483d8d_idx'),
        ),
    ]
