# Generated by Django 6.0.3 on 2026-04-26 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_aircraft_ai_registr_47b3ca_idx_and_more'),
        ('airlines', '0002_airline_airlines_ai_name_d4975d_idx_and_more'),
        ('airports', '0003_airport_airports_ai_name_b30727_idx_and_more'),
        ('flights', '0006_flight_last_synced_at_alter_flight_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual arrival'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual departure'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='aircraft.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines.airline', verbose_name='Airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airports.airport', verbose_name='Destination airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Flight number'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last synchronized at'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='live_altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Live altitude'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='live_direction',
            field=models.FloatField(blank=True, null=True, verbose_name='Live direction'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Live latitude'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Live longitude'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='live_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Live speed'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airports.airport', verbose_name='Origin airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.DateTimeField(verbose_name='Scheduled arrival'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_departure',
            field=models.DateTimeField(verbose_name='Scheduled departure'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API Synced')], db_index=True, default='local', max_length=10, verbose_name='Source type'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='actual_arrival_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual arrival snapshot'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='actual_departure_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual departure snapshot'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='arrival_delay_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Arrival delay minutes'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='change_summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Change summary'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('status', 'Status Change'), ('schedule', 'Schedule Change'), ('live', 'Live Data Change'), ('mixed', 'Mixed Change')], default='status', max_length=20, verbose_name='Change type'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='departure_delay_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Departure delay minutes'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='flights.flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='is_disruption_event',
            field=models.BooleanField(default=False, verbose_name='Disruption event'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='live_data_changed',
            field=models.BooleanField(default=False, verbose_name='Live data changed'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='new_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='New status'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20, null=True, verbose_name='Previous status'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='schedule_changed',
            field=models.BooleanField(default=False, verbose_name='Schedule changed'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='scheduled_arrival_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled arrival snapshot'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='scheduled_departure_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled departure snapshot'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='source_type_snapshot',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API Synced')], default='local', max_length=10, verbose_name='Source type snapshot'),
        ),
        migrations.AlterField(
            model_name='flightstatushistory',
            name='status_changed',
            field=models.BooleanField(default=False, verbose_name='Status changed'),
        ),
    ]
