# Generated by Django 6.0.3 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_alter_airport_city_alter_airport_country_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['name'], name='airports_ai_name_b30727_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['iata_code'], name='airports_ai_iata_co_ea5b11_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['icao_code'], name='airports_ai_icao_co_60333d_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='airports_ai_city_d30040_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country'], name='airports_ai_country_3d1a1e_idx'),
        ),
    ]
