# Generated by Django 6.0.3 on 2026-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_airport_airports_ai_name_b30727_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['is_active'], name='airports_ai_is_acti_6c812b_idx'),
        ),
    ]
