# Generated by Django 6.0.3 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
        ('airlines', '0002_airline_airlines_ai_name_d4975d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['registration_number'], name='aircraft_ai_registr_47b3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['model'], name='aircraft_ai_model_21352b_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['aircraft_type'], name='aircraft_ai_aircraf_09cde2_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['status'], name='aircraft_ai_status_041aad_idx'),
        ),
    ]
