# Generated by Django 6.0.3 on 2026-03-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0004_flight_live_altitude_flight_live_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline_name', models.CharField(max_length=150)),
                ('origin_iata', models.CharField(max_length=10)),
                ('destination_iata', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('source_type', models.CharField(max_length=10)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Change'), ('schedule_change', 'Schedule Change'), ('source_change', 'Source Change'), ('update', 'Update')], default='update', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Flight History',
                'verbose_name_plural': 'Flight History',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
