# Generated by Django 6.0.3 on 2026-03-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighthistory',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='live_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='live_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='live_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='previous_scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='previous_scheduled_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='previous_source_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='sync_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='integrations.apisynclog'),
        ),
        migrations.AlterField(
            model_name='flighthistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Change'), ('schedule_change', 'Schedule Change'), ('source_change', 'Source Change'), ('update', 'Update'), ('sync_snapshot', 'Sync Snapshot')], default='update', max_length=20),
        ),
    ]
