# Generated by Django 6.0.3 on 2026-04-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_flighthistory_actual_arrival_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightHistory',
        ),
    ]
