# Generated by Django 6.0.3 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['name'], name='airlines_ai_name_d4975d_idx'),
        ),
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['iata_code'], name='airlines_ai_iata_co_56ada0_idx'),
        ),
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['icao_code'], name='airlines_ai_icao_co_0dadcb_idx'),
        ),
    ]
