# Generated by Django 6.0.3 on 2026-05-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_airline_airlines_ai_name_d4975d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/', verbose_name='Airline logo'),
        ),
    ]
