# Generated by Django 6.0.3 on 2026-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_airline_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code, for example: FR, DE, US, TR.', max_length=2, null=True, verbose_name='Country code'),
        ),
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['country'], name='airlines_ai_country_0db032_idx'),
        ),
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['country_code'], name='airlines_ai_country_2f6873_idx'),
        ),
    ]
